version: "3.7"
services:  
  config-server:
    image: ms-config-server:v1
    container_name: config-server
    ports: 
      - "8888:8888"
    restart: always
    networks:
      - microservicio
  
  eureka-server:
      image: ms-eureka-server:v1
      container_name: eureka-server
      ports: 
        - "8761:8761"
      restart: always
      networks:
        - microservicio

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "54320:5432"
    environment:
      - "POSTGRES_PASSWORD=2020" 
      - "POSTGRES_DB=usuarios"
    restart: always
    networks:
      - microservicio

  microservicio-usuario:
      image: ms-usuario:v1
      container_name: microservicio-usuario
      depends_on:
      - config-server
      - eureka-server
      - postgres
      restart: always
      networks:
        - microservicio

  microservicio-oauth:
      image: ms-oauth:v1
      container_name: microservicio-oauth
      ports: 
        - "9100:9100"
      depends_on:
        - config-server
        - eureka-server
        - microservicio-usuario
      restart: always
      networks:
        - microservicio
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    restart: always
    networks:
      - microservicio

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2020"
      - "MYSQL_DATABASE=productos"
    restart: always
    networks:
      - microservicio
    
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
      - "STORAGE_TYPE=mysql"
      - "MYSQL_HOST=mysql"
      - "MYSQL_TCP_PORT=3306"
      - "MYSQL_USER=zipkin"
      - "MYSQL_PASS=zipkin"
    restart: always
    networks:
      - microservicio

  microservicio-producto:
      image: ms-producto:v1
      container_name: microservicio-producto
      depends_on:
        - config-server
        - eureka-server
        - mysql
      restart: always
      networks:
        - microservicio

  microservicio-item:
      image: ms-item:v1
      container_name: microservicio-item
      depends_on:
        - config-server
        - eureka-server
        - microservicio-producto     
      restart: always
      networks:
        - microservicio

  zuul-server:
      image: ms-zuul-server:v1
      container_name: zuul-server
      ports: 
        - "8090:8090"
      depends_on:
        - config-server
        - eureka-server
        - microservicio-producto
        - microservicio-item
        - microservicio-usuario
        - microservicio-oauth        
      restart: always
      networks:
        - microservicio

networks:
  microservicio:
