version: "3.7"
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2020"
      - "MYSQL_DATABASE=productos"
    restart: always
    networks:
      - microservicio

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    restart: always
    networks:
      - microservicio

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
      - "STORAGE_TYPE=mysql"
      - "MYSQL_HOST=mysql"
      - "MYSQL_TCP_PORT=3306"
      - "MYSQL_USER=zipkin"
      - "MYSQL_PASS=zipkin"
    restart: always
    networks:
      - microservicio

networks:
  microservicio:
