version: "1"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - microservicio

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2020"
      - "MYSQL_DATABASE=productos"
    networks:
      - microservicio
  
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "54320:5432"
    environment:
      - "POSTGRES_PASSWORD=2020" 
      - "POSTGRES_DB=usuarios"
    networks:
      - microservicio

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
      - "STORAGE_TYPE=mysql"
      - "MYSQL_HOST=mysql"
      - "MYSQL_TCP_PORT=3306"
      - "MYSQL_USER=root"
      - "MYSQL_PASS=2020"
    networks:
      - microservicio

  config-server:
    image: config-server:v1
    container_name: config-server
    ports: 
      - "8888:8888"
    networks:
      - microservicio
  
  eureka-server:
      image: eureka-server:v1
      container_name: eureka-server
      ports: 
        - "8761:8761"
      networks:
        - microservicio

  microservicio-usuario:
      image: microservicio-usuario:v1
      container_name: microservicio-usuario
      ports: 
        - "8002:8002"
      networks:
        - microservicio

  microservicio-oauth:
      image: microservicio-oauth:v1
      container_name: microservicio-oauth
      ports: 
        - "9100:9100"
      networks:
        - microservicio
  
  microservicio-producto:
      image: microservicio-producto:v1
      container_name: microservicio-producto
      ports: 
        - "8001:8001"
      networks:
        - microservicio

  microservicio-item:
      image: microservicio-item:v1
      container_name: microservicio-item
      ports: 
        - "8002:8002"
      networks:
        - microservicio

  zuul-server:
      image: zuul-server:v1
      container_name: zuul-server
      ports: 
        - "8090:8090"
      networks:
        - microservicio

networks:
  microservicio:
