version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "54320:5432"
    environment:
      - "POSTGRES_PASSWORD=2020" 
      - "POSTGRES_DB=usuarios"
    restart: always
    networks:
      - microservicio

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33060:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=2020"
      - "MYSQL_DATABASE=productos"
    restart: always
    networks:
      - microservicio

networks:
  microservicio:
