apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-producto
  labels:
    app: ms-producto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-producto
  template:
    metadata:
      labels:
        app: ms-producto
    spec:
      containers:
      - name: ms-producto
        image: ms-producto
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8002
