apiVersion: v1
kind: Pod
metadata:
  name: microservicio-producto
  labels:
    name: microservicio-producto
spec:
  containers:
  - name: microservicio-producto
    image: ms-producto
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8002
