apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: ms-eureka-server:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "700m"
        ports:
        - containerPort: 8761
