apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-productos
  labels:
    app: microservicio-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-productos
  template:
    metadata:
      labels:
        app: microservicio-productos
    spec:
      containers:
      - name: microservicio-productos
        image: ms-producto:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"        